### PR TITLE
fix nested query parameters

### PR DESCRIPTION
**Pull request by mgartner**
@pon @leore @elnaz @robinjoseph08

### CODE REVIEW

**Comment by robinjoseph08** [comment]
Do we not need to be testing this?

**Comment by pon** [comment]
LGTM

**Comment by mgartner** [comment]
all get requests flow through this code, so if those pass we should be good.

**Comment by robinjoseph08** [comment]
I'm wondering why this issue didn't show up before?

**Comment by mgartner** [comment]
oh because there are no tests that use nested hashes....

**Comment by robinjoseph08** [comment]
Shouldn't there be?

**Comment by mgartner** [comment]
I added an issue to tackle it later: https://github.com/lob/lob-ruby/issues/111

**Comment by robinjoseph08** [comment]
sounds good :+1: LGTM

**Pull request merged**
