### PR TITLE
Remove vcr

### PR DESCRIPTION
**Pull request by mgartner**
@robinjoseph08

### CODE REVIEW

**Comment by pon** [comment]
Some of these changes are breaking right?

**Comment by robinjoseph08** [comment]
@pon Right. We'll be cutting a new major version once we merge in #116 too

**Comment by pon** [comment]
Ok sounds good

**Comment by mgartner** [comment]
@robinjoseph08 your commit LGTM.

**Comment by robinjoseph08** [comment]
@mgartner looks like you got all the instances of VCR so LGTM

**Pull request merged**
