### PR TITLE
chore(resources-namespace): Move V1 namespace to Resources namespace

### PR DESCRIPTION
**Pull request by mpiercy827**
**What**

Rename the `V1` namespace to `Resources` and move `client.rb` out of the `lib/lob/resources` directory.

**Why**

Originally, we were thinking of removing the `V1` namespace altogether, and bringing the resources up to the `Lob` namespace. However I think this would clutter up the `Lob` namespace unnecessarily, especially since these resources aren't going to be accessed by users, who are instead interfacing with the `Lob::Client`.

**Notes**

The next (and hopefully final) step before releasing v3.0.0 is to change the configuration.

### CODE REVIEW

**Comment by itsachen** [comment]
LGTM

My only concern is that we'd be removing the major version of the API from the wrapper. I agree that it doesn't need to be as explicit as a namespace, but would it be helpful to include that information somewhere? Like a `.lob_api_version` file?

I'm just thinking ahead - if Lob API progresses to v2 and beyond it'd be easier to distinguish which versions of lob-ruby are compatible with which versions of the API.

**Comment by itsachen** [comment]
Hm, I think I spoke before digging deeper into the repo. There seems to be `/lob/version.rb`, maybe this is the information I'm thinking about.

**Comment by mgartner** [comment]
@itsachen let's chat IRL regarding API version

**Comment by mpiercy827** [comment]
The information in `lib/lob/version.rb` is actually the version of the wrapper, not the API. Once we are ready to release, that will be bumped up to 3.0.0.

While it is hidden a bit, we still have the major version of the API in the wrapper [here](https://github.com/lob/lob-ruby/pull/152/files#diff-394509fc16f2e204e447c1ea54fe53d3R95) in the `base_url` method of the `ResourceBase` class.

I agree about keeping a record of the API version, but I'm not sure whether that should be a top level namespace or not. Definitely open to ideas though!

**Pull request merged**
