### PR TITLE
add test for routes list endpoint with multiple zip codes

### PR DESCRIPTION
**Pull request by mgartner**
I added a test that passes multiple zip_codes to the `GET /v1/routes` endpoint. This serves as not only a good test but also as an example for users trying to fetch a combination of routes.

### CODE REVIEW

**Comment by brianseitel** [comment]
lgtm

**Comment by ami** [comment]
@mgartner can you add a PR to lob.com too to update the docs?

**Comment by robinjoseph08** [comment]
LGTM

**Comment by mgartner** [comment]
@ami coming right up

**Pull request merged**
