### PR TITLE
fix errors

### PR DESCRIPTION
**Pull request by bgoldman**

### CODE REVIEW

**Comment by mgartner** [comment]
@bgoldman thanks for the input. I'm going to make a new PR real quick to just get rid of the `format_address_params` method entirely. And for the error handling I'm gonna merge in #115.

**Comment by bgoldman** [comment]
@mgartner #115 doesn't solve the problem with the error message. I believe the field got renamed in the API to `errors` and now returns an array, while in this code, it is called `error` and expects a string. My code solves that problem, this code just ignores the actual problem and raises an error when no error should be raised.

**Comment by mgartner** [comment]
@bgoldman Actually there was a change in the latest API version to change the field from `errors` to `error`. My bet is that you're not on the most recent API version, but are trying to use the most recent lob-ruby version, which doesn't support older versions of the API. I believe the latest version of lob-ruby that will support your version of the API would be v1.10.0.

If you'd like to upgrade your API version, you can do so from https://dashboard.lob.com/#/settings/keys. When you click on the upgrade button, it will tell you all the breaking changes that you will need to address. You can also temporarily test your implementation with a newer version of the API by passing a `Lob-Version` header: https://lob.com/docs#version

**Comment by mgartner** [comment]
Closing in favor of #116.

**Pull request closed without merging**
