### PR TITLE
use size in postcard example instead of setting

### PR DESCRIPTION
**Pull request by mgartner**
In preparation for 2015-12-22.

### CODE REVIEW

**Comment by elnaz** [comment]
LGTM

**Comment by robinjoseph08** [comment]
is there a reason we have this special api key specifically for ruby? why cant it use the same one we use in the docs?

**Comment by mgartner** [comment]
I created a different test account for each wrapper to avoid 429s.

**Comment by mgartner** [comment]
^ I couldn't get all these builds to pass with the same API key.

**Comment by robinjoseph08** [comment]
:+1: good thinking. That'll be helpful in the future too to not have to worry about it.

**Comment by robinjoseph08** [comment]
LGTM

**Pull request merged**
