### PR TITLE
Pass through proxy to rest-client if supplied

### PR DESCRIPTION
**Pull request by drcapulet**

### CODE REVIEW

**Comment by ShariqT** [comment]
Thanks for using Lob! I'll take a look as to why the tests are failing and get back to you.

**Comment by colin-garcia** [comment]
Hey @ShariqT thanks for looking into this Any updates on the test failures?

**Comment by ShariqT** [comment]
@colin-garcia This was something on our end when moving from TravisCI to GH Actions. We needed to setup a workflow around managing PRs from forked repos. Forked repos don't have access to the repo secrets, which means that tests aren't going to run correctly. I looked this PR and all of the test pass, so we are good. It will be merged.

**Comment by colin-garcia** [comment]
Thank you so much @ShariqT!

**Review by ShariqT — APPROVED** [review]

**Pull request merged**
